spring.application.name=sankuni
server.port=8080

# ==========================================
# CONEXIÓN A POSTGRESQL (dvSnkuni)
# ==========================================
spring.datasource.url=jdbc:postgresql://localhost:5432/dvSnkuni?stringtype=unspecified
spring.datasource.username=postgres
spring.datasource.password=admin123
spring.datasource.driver-class-name=org.postgresql.Driver

# ==========================================
# CONFIGURACIÓN DE JPA / HIBERNATE
# ==========================================
# validate: Comprueba que las tablas de Java coincidan con las de PostgreSQL sin alterarlas
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ==========================================
# CONFIGURACIÓN JWT (SANKUNI)
# ==========================================
# Reemplaza la línea actual por esta:
sankuni.jwt.secret=5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
sankuni.jwt.expiration=86400000

# ==========================================
# CONFIGURACIÓN DE EMAIL (SMTP)
# ==========================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=jhalebet1994@gmail.com
spring.mail.password=uednrgvkiojgparg
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true