spring.application.name=sankuni
server.port=8080

# ==========================================
# CONEXIÓN A POSTGRESQL (dvSnkuni)
# ==========================================
spring.datasource.url=jdbc:postgresql://localhost:5432/dvSnkuni
spring.datasource.username=postgres
spring.datasource.password=ansu22
spring.datasource.driver-class-name=org.postgresql.Driver

# ==========================================
# CONFIGURACIÓN DE JPA / HIBERNATE
# ==========================================
# validate: Comprueba que las tablas de Java coincidan con las de PostgreSQL sin alterarlas
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ==========================================
# CONFIGURACIÓN JWT (SANKUNI)
# ==========================================
sankuni.jwt.secret=7d32456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef
sankuni.jwt.expiration=86400000